### ISSUE TITLE
Searching color by name?

### ISSUE THREAD

**Issue by Tosh0kan** [meodai/color-name-api#4]
Is it possible to use the curl command to search the API for color names?

**Comment by meodai** [comment]
It was, but it was abused by some webshops. So I had to turn it off. The feature is still supported by the code but I have blocked the endpoint: https://api.color.pizza/v1/names/?name=Flamingo

You can just host the API somewhere of your choice and it will work.

**Comment by meodai** [comment]
@Tosh0kan the endpoint works again, it has a rate limitation though! Have fun
